-- ============================================================
-- Group chat migration: replace test messages with Circle history
-- April 21–25, 2026 | 65 messages | timestamps in BST (UTC+1)
-- Sequential seconds added within each minute to preserve order
-- ============================================================

-- Step 1: Remove existing test messages
DELETE FROM community_messages WHERE chat_id = 'group';

-- Step 2: Insert Circle chat history
INSERT INTO community_messages (chat_id, email, name, content, media, created_at) VALUES
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'HELLO EVERYONE! We are live! We''ve made it finally 🎹', '[]', '2026-04-21 09:06:00+01'),
  ('group', 'danielduordoe@yahoo.co.uk', 'Daniel Duordoe', 'Nice!', '[]', '2026-04-21 09:09:00+01'),
  ('group', 'mortenjensen@me.com', 'Morten Jensen', 'Congrats to you Matthew and yay for the rest of us. I look forward to exploring everything 😊', '[]', '2026-04-21 09:11:00+01'),
  ('group', 'czarkwas96@gmail.com', 'Somraj Biswas', 'Hello Everyone, looking forward to be a part of this experience.', '[]', '2026-04-21 09:11:01+01'),
  ('group', 'davidwhamilton79@gmail.com', 'David Hamilton', 'Hello all. This is a great idea Matthew.', '[]', '2026-04-21 09:12:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Thank you @Morten Jensen, I hope you all find this place useful and thank you @David Hamilton!', '[]', '2026-04-21 09:14:00+01'),
  ('group', 'lambsarahlouise@gmail.com', 'Sarah Lamb', 'Hello! This is exciting.', '[]', '2026-04-21 09:16:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'If there or any problems with the Practice Hub site or anything like that, let me know....ive been testing everything in solitude so hopefully everything functions as it should 😀', '[]', '2026-04-21 09:17:00+01'),
  ('group', 'davidwhamilton79@gmail.com', 'David Hamilton', 'I get the impression most people here are beginners like myself. Id be curious to know how you''re all learning.  Are you using method books like me or do you have a teacher?', '[]', '2026-04-21 09:19:00+01'),
  ('group', 'alexey@peshekhonov.com', 'Alexey Peshekhonov', 'Practice log requires to choose a piece to log something. And requirements for beginner pieces for me are like 50% I can''t do that yet and 50% I can''t even understand what''s required. So how can I log if I am the real beginer?', '[]', '2026-04-21 09:19:01+01'),
  ('group', 'lambsarahlouise@gmail.com', 'Sarah Lamb', 'David, I''m a beginner too. I''m using the Faber adult adventure books, as well as an app/website (not sure I can name it) that has lots of video tutorials and lessons (it''s not one of those synethesia apps, it really is teaching you how to read music)', '[]', '2026-04-21 09:22:00+01'),
  ('group', 'jifupt@gmail.com', 'Joao Carvalho', 'Hello everyone! I''m not sure what to expect from this community, but saw there was a money-back option so I figured I had nothing to lose! :) I''m totally new to the piano (started less than 2 months ago) and found some of Matthew''s videos on YouTube to be very helpful, hence how I got here!', '[]', '2026-04-21 09:23:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', '@Alexey Peshekhonov At the very very beginning, it''s a good idea to start with either a beginner book (to help start to read notes, understand rhythms etc..), such as the one Sarah mentioned, or by jumping straight into one of the beginner pieces and problem solving. If there are markings you don''t understand...or you need a methodology for working out the notes...I''m happy to help.  I would have a look through some of the pieces that are marked as Beginner and find one that looks the most approachable (even if it still looks a little challenging). Many people find that at the start of learning a piece that it looks somewhat alien, but as you start to work out what everything means, it becomes a bit clearer.', '[]', '2026-04-21 09:26:00+01'),
  ('group', 'michaelpage05@hotmail.co.uk', 'Michael Page', 'Its finally here!!! @Matthew Cawood I have been following you for some time and have enjoyed your content and the way you explain them.
I am a drummer from the UK and have tinkered with the piano one and off for some time. I have a large rang of musical interests. I would love to be able to play classical and I had a fascination with jazz as a child. I am a life member of Musora for there drumming content but recently been going through there pianote learning path witch has been fun. But they mainly focus on playing songs in bands. So looking foreword to getting in to classical pieces. I would class my self as a beginner.', '[]', '2026-04-21 09:28:00+01'),
  ('group', 'jifupt@gmail.com', 'Joao Carvalho', '@Matthew Cawood was watching a video of yours and something got me curious: why do you have the volume bar of the piano disabled/quite low? Do you have some other way to output the sound? I ask as your piano looks just like mine!
Attachment image', '[]', '2026-04-21 09:28:01+01'),
  ('group', 'lambsarahlouise@gmail.com', 'Sarah Lamb', '@Michael Page thats what I am doing too (Pianote)', '[]', '2026-04-21 09:29:00+01'),
  ('group', 'davidwhamilton79@gmail.com', 'David Hamilton', 'Ive enjoyed taking part in the /Pianolearning subreddit but this seems to be taking that community approach to a whole other level with the resources and feedback etc', '[]', '2026-04-21 09:29:01+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', '@Joao Carvalho I do! I use a plugin called Keyscape for a better piano sound and the sound comes through my in-ear monitors so that if I''m talking at the same time in videos, the piano isn''t also picked up by the microphone.', '[]', '2026-04-21 09:30:00+01'),
  ('group', 'lambsarahlouise@gmail.com', 'Sarah Lamb', 'Does anyone else have any other musical experience? I started with the recorder as most children seem to do in primary school, and then switched to the Bb clarinet which I stuck with until I got to about 16 and packed it all in. I wish I had continued with it. I started teaching myself the piano earlier this year at the age of 36, and I''m definitely finding learning the bass clef difficult!', '[]', '2026-04-21 09:31:00+01'),
  ('group', 'mflander4@gmail.com', 'Mike Flander', 'Hi All! Been playing since last June from Minnesota, USA! Excited for this community. I hope it can help keep up the motivation to keep pushing forward.', '[]', '2026-04-21 09:31:01+01'),
  ('group', 'hivoltageroc@aol.com', 'Howard Garner', 'Hi.  I have a teacher and am currently studying grade 4 ABRSM.  I would like to get into jazz/blues and I subscribe to other sites re this.  What I like about having a teacher, especially as a very late adult learner, is that it gives you focus as opposed to moving from one thing to another without making real progress.', '[]', '2026-04-21 09:33:00+01'),
  ('group', 'm.gepert@gmail.com', 'Mateusz Gepert', 'Mateusz from Poland here, for 18 years heavy notes dropper on bass guitar switched to piano year ago 😂 so you can consider me a beginner 😉 . I''m self learner using so far playground sessions app and practising with Zach Evans technique oriented course. I struggle most with hand coordination, side reading, theory, technique and motivation so literally everywhere is some room for improvement 😃', '[]', '2026-04-21 09:33:01+01'),
  ('group', 'confi1@hotmail.com', 'Kelly Williams', 'Hi everyone!! It''s nice to not feel like I''m not the only adult learner!! 😁', '[]', '2026-04-21 09:33:02+01'),
  ('group', 'janesimpson50@hotmail.com', 'Jane Simpson', 'Hello Matthew and everyone, I''m Jane from London, almost a total beginner but practising hard to get better. I''m using a mix of Piano Adventures and Alfred''s Adult course and dipping into older books as I like to have a bit of variety and do lots of exercises - I''m quite old so co-ordinating brain and hands needs a lot of work! Currently also working hard for Grade 2 recorder', '[]', '2026-04-21 09:39:00+01'),
  ('group', 'connieuitsu@gmail.com', 'Connie Witzoe', 'Hi from Norway! (Well, Wales really, but I''m from Norway)
I took piano lessons for 3 years, 20 years ago.
Started teaching myself again in December.
Really excited about The Practice Room and what it can do for us who are teaching ourselves to play. Great idea!  🙂', '[]', '2026-04-21 09:40:00+01'),
  ('group', 'norman.jaillet@gmail.com', 'Norman Jaillet', 'Hi folks - (sorry for the long intro)  My name is Norman and I live in the Boston area. Played accordion until I was about 15 and left; sports. girls etc. I was a Director of Liturgy for 15 years (retired 1999), plunked out the tunes and directed the choirs. I have sung in the churches around Boston  and did some musical theater as well. So I do have a "base." Fast forward 50 years and here I am. I''m a retired exec (now a headshot photog) and needed something to fill in the time. The wife suggested I start keyboards ... Purchased digital keyboards and upgraded over the past 2 years and now have a lovely Schimmel K132. Was doing online tutorials and decided to get a teacher and have been working with him for almost 2 years. Still not confident with the left hand but getting better. I had Dupuytrens surgery on my right hand in August, couldn''t do much for 7 weeks last summer/fall, and feeling better. Gearing up for a student recital playing Chopin Prelude 3 and 7. Working on Schumann Of Foreign Lands and Peoples for the past few weeks. Going well! Looking forward to continued motivation from Matthew and this group.', '[]', '2026-04-21 09:43:00+01'),
  ('group', 'nivash.singh66@gmail.com', 'Nivash Singh', 'Hey All - looking forward to this journey with all of you. Nivash from South Africa!', '[]', '2026-04-21 09:53:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Now that we''re all in here. It would be great to know what your biggest challenge on the piano is right now? It would be nice to see what kind of things people are looking for help with.', '[]', '2026-04-21 10:18:00+01'),
  ('group', 'davidwhamilton79@gmail.com', 'David Hamilton', 'For me its finger independence and being able to play with both hands smoothly. I play classical guitar which seems to help a bit with it but its a very different technique on piano.', '[]', '2026-04-21 10:19:00+01'),
  ('group', 'wg33@live.co.uk', 'Wendy Grimshaw', 'Hi everyone,  I started teaching myself a couple of years ago, I''m mainly following  a couple of beginner method books and YouTube tutorials. I''m looking forward to finding some inspirational new pieces to try at my level. As I had a little musical experience  I find it fairly easy to read the treble clef, but am finding reading the bass clef more of a challenge!', '[]', '2026-04-21 10:24:00+01'),
  ('group', 'hivoltageroc@aol.com', 'Howard Garner', 'Biggest problem is rhythm and timing.  I must use the metronome more to create a natural rhythm.  I’ve also just started recording myself which is real eye opener.', '[]', '2026-04-21 10:34:00+01'),
  ('group', 'seyb1989@gmx.net', 'Sebastian Weiß', 'Hi folks, my name is Sebastian and I am from Germany, near Frankfurt. I am 36 years old and started playing the piano in January 2023 and I take weekly 1-on-1 personal lessons (45 minutes) since I started. Currently I am learning "Le Onde" from Einaudi and the Sonatina in C major (op. 36/1) from Clementi. I want to advance in dynamics and articulation as well as keeping the rhythm on harder passages. I really enjoy the music from Hans Zimmer and Ludovico Einaudi, so one of my goals is learning to play "Experience" and "Interstellar" properly. In contrast I also listen to Rammstein, who have some awesome pieces for the piano as well (e.g. "Sonne").', '[]', '2026-04-21 10:47:00+01'),
  ('group', 'georgejn88@gmail.com', 'John George', 'Complete beginner aged 37 who started two month ago. Living on the East Coast of the US. Was happy to see the first Q&A was at a time that I can attend. I feel like Matt is doing the hard work of starting that close to midnight in his time.
I just want to get good enough to be able to learn pieces on my own and look forward to where I''ll be in three years. I really want to be able to play Passacaglia and can play the right hand really well. The left hand decent, but together is certainly more difficult than I thought it would be. Its like I forgot how to play either hand when trying to do it together.
I enjoy slower beautiful songs (Van Gogh is another I want to learn) and am excited to have access to pieces I can practice with to get good enough to eventually learn some beautiful songs.', '[]', '2026-04-21 10:55:00+01'),
  ('group', 'alejandrohitti@gmail.com', 'Alejandro Hitti', 'Hey everyone! I''m also a beginner I guess? I used to learn pieces by memorizing them, so I can play a few pieces that are far beyond my level quite well I think, but I just got a Kawai ES120 for my bday like 2 weeks ago, and I got the Faber Adult Adventures book. Almost done with chapter 4! I''ll upload some pieces later if I get a chance. I guess my goal is to slowly learn actual theory and be able to read/sight-read at a level 5-6 so I can play the pieces I enjoy (Disney, anime, game songs). I know that might take 3-5 years, but I''m willing to put in the work :)', '[]', '2026-04-21 11:16:00+01'),
  ('group', 'tdalavoy@gmail.com', 'Tulika Dalavoy', 'Hi everyone. Glad to be part of this community. I am from India. I am playing piano since 3 years, currently in Grade 3 Trinity. I am taking online classes from a teacher. In addition to Western pieces, I also play Bollywood songs. I would really like to focus more on Western classical. I especially love Chopin''s pieces, the waltz and nocturnes and hope to be able to play them well eventually.  I am currently working on Rondo alla turca. Having some challenges with finger control in some places.', '[]', '2026-04-21 12:08:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Hello gang, I''ve now updated the pieces database to include an "Absolute Beginner" rating for those that were concerned looking at the beginner pieces. I''ve added another selection of 6-7 pieces along with their sheet music so you have an easier first step you can take. For those that are a little further with reading, these are also great pieces to be used as sight reading exercises (after my sight reading book of course 😂 ). Let me know if there are any problems!', '[]', '2026-04-21 12:12:00+01'),
  ('group', 'jeff_epstein@yahoo.com', 'Jeff L Epstein', 'Hi, everyone.
My name is Jeff and I''m in New Jersey right across from Philadelphia. I''m a classically trained vocalist and for the past two years have been working full-time as a singer in senior-living centers.
More than three decades ago, I played piano for maybe a year but let it go until July 5th, 2024, when I purchased my (wonderful) Roland FP-30X. In the past year and nine months, I''ve learned around fifteen piano pieces, featuring five full-length pieces by my favorite composer, Scott Joplin. (My favorite musical artist overall is Billy Joel!)
I''m very happy with how far I''ve come, knowing how long I''ve been at this, but when it comes to improvising, such as over lead sheets, I''m a complete beginner. Improvising stresses me out! I like reading sheet music because it tells me exactly what to do and when to do it. (I''m completely self-taught.) I need to greatly improve with theory as well.
My long-term goal is to sing and play at the same time, but it feels many years off. I like my singing and I like my playing, but when I try them at the same time, I don''t like either. Maybe someday they''ll come together, but for now, I''m just enjoying them separately.
Regarding the piano pieces I''m currently playing, my goal is to make them as musical as possible. Aside from making some obvious small mistakes (how do professional players at least give the appearance of never making mistakes???), I think I''ve achieved that. I''ve played the songs many hundreds of times (especially before my singing performances), which seems to be the only way to let go of the THINKING and start FEELING. Then you can loosen up and play around with flourishes, dynamics, pedaling and so on.
Last night, I recorded all five of my Scott Joplin pieces. I''ll gradually post everything here.
Thanks to Matt for this community. There are several good music/piano people on YouTube, but your not being a frenetic personality compared to some others is a big reason I keep coming back to your channel.  :)
I look forward to meeting everyone and playing together!', '[]', '2026-04-21 12:54:00+01'),
  ('group', 'chris@stellardad.net', 'Chris R', 'Hey all! I''ve been playing off-and-on (mostly off) for as long as I can remember (late 30s now). Only recently have I tried to push my skill level beyond my comfort zone. I''m somewhere in the upper intermediate skill level (maybe?) and have felt stuck here for years. My biggest challenge right now is learning to play two different voices with the right hand, which seems to come up more often than not in the pieces I''m choosing. My goals here are to help me focus on being more serious about practice (accountability and finding the right pieces) and to support @Matthew Cawood! I''m self taught and I''m suspicious that I may have major gaps in my basic understanding, which is how I came across the channel to begin with. Hoping this will level it up. Like @Sebastian Weiß I''ve been on a Einaudi kick and the latest piece I learned was Nuvole Bianche.', '[]', '2026-04-21 13:35:00+01'),
  ('group', 'larahnja@gmail.com', 'Larah Szemczak', 'Hello everyone! My name is Larah, I’m 24 years old and I’m from Brazil. It’s been a year since I got my first piano (it’s a digital piano, but I plan to buy an acoustic one in a few years).
Since then, I’ve been practicing on my own. I’ve already learned parts of a few pieces I like, but I’m still struggling to improve and make consistent progress. Sometimes, I feel a bit lost when it comes to practicing technique.
I’m really happy to join this community. I’m still figuring out how to set clear goals and build an effective practice routine, but being here and following Matthew’s content already makes things feel much clearer and more manageable.', '[]', '2026-04-21 13:47:00+01'),
  ('group', 'mortenjensen@me.com', 'Morten Jensen', 'Hi from Denmark (again). I''ve been playing since Jan-2025 and have been using various apps, an online course (which was too difficult) and a bit of the faber adult adventures with video guidance through "piano roadmap", which is pretty awesome if you have the time. My main challenge right now is finding time since my daughter came into the world a few months back, but other than that I think structure and finding the right pieces for my level is hardest. I would love to learn Ludovico Einaudi (went to Edinburg to watch him last summer) and film music such as Hans Zimmer but also various classical pieces in general.', '[]', '2026-04-21 14:55:00+01'),
  ('group', 'cecile.dautriat@gmail.com', 'Cécile Dautriat', 'Hello everyone!
Where you''re from: Unsure. I now live in Detroit, Michigan after a short stay in Graz, Austria. I’m French.
How long you''ve been playing: My one-year piano anniversary was last week.
What you''re currently working on: I’m using the RCM syllabus as my general roadmap (and I binge-watch Matt’s videos, of course). I started level 2 last week, currently working on “Razzle Dazzle”, “Canon in Am”, “Impertinence”, and “Sick Doll”.
Your level: Beginner
Your goals: Just having fun and enjoying the process of learning how music works.
I know lessons would help me progress faster, but my schedule just won''t cooperate for a weekly commitment. “The Practice Room” might be the best solution for me and I’m looking forward to learning with everyone.', '[]', '2026-04-21 14:56:00+01'),
  ('group', 'andilammer@gmail.com', 'Andreas Messner', 'This community already feels like "home" to me; I love reading all these introductions! ❤️
Anyway, I am from Styria, Austria, and I''m 35 years old. I started playing at the beginning of 2026. I got a keyboard for Christmas after showing interest in learning again, having previously taken two years of lessons when I was 12.
At first, I started learning just by watching songs on YouTube. Soon after, I discovered @Matthew Cawood videos, which really sparked my enthusiasm for music theory and classical pieces—something I hadn''t thought about playing before. I started learning the instrument based on those recommendations. Also bought a proper E piano pretty fast😅.
I try not to let any specific skill fall too far behind, and I aim to use my practice time as efficiently as possible (mostly! 😉). This has already brought me to a point where, sometimes, I can sit down in the evening and just improvise and be able to kinda "float away" with the music—at a beginner level, at least—and I absolutely love it 🥰.
So, I guess I’m doing alright? 🤷‍♂️😅', '[]', '2026-04-21 15:02:00+01'),
  ('group', 'dominik.talik@gmail.com', 'Dominik Talik', 'Hello. My name is Dominik, and I live near Krakow, Poland. I started playing the keyboard when I was around 16. I was completely self-taught and didn''t focus strictly on the piano, although that was always my dream (playing without weighted keys wasn''t the best experience). I gave up around 21, thinking I had started too late. Last year, shortly before my 37th birthday, I heard a piano piece I wanted to learn so badly that I retrieved my old keyboard from the attic. I soon replaced it with a Yamaha P-45 and started taking structured courses using available online resources. I am still self-taught, now about seven months into a daily practice routine. Besides the piano, I am a passionate landscape photographer. Epic photography trips are currently paused for dad duties with my two-year-old, so I am channeling my creative energy into learning the piano at nights. I am mostly interested in soundtracks, epic or melancholic pieces, and piano arrangements of iconic popular songs. Excited to join this community!', '[]', '2026-04-21 15:23:00+01'),
  ('group', 'shaun.purbrick@gmail.com', 'Shaun Purbrick', 'Hi. My name’s Shaun. I live on the North Norfolk coast in the UK. I took up piano when I was 30 but gave up after about 18 months due to work commitments (and not practising!). At 40, I took up guitar and learned to read music. Now 55, I am seriously studying (and massively enjoying) piano once more. I got a tutor last summer, have weekly lessons, and I’m currently studying Trinity grade 4. My musical tastes are very varied. I have been learning on a digital piano at home and recently purchased an acoustic as well. I’m finding it a challenge to play softly and quietly on the acoustic (especially left hand) so any tips would be welcome! My goal is to be the best pianist I can be and to develop a deep understanding of music theory.', '[]', '2026-04-21 15:52:00+01'),
  ('group', 'danielduordoe@yahoo.co.uk', 'Daniel Duordoe', 'Hello everyone. I''m Daniel. I resumed playing the piano earlier this year after taking a long break. My goal is to regain my musical skills and eventually improve even further.', '[]', '2026-04-21 17:39:00+01'),
  ('group', 'lucas.fr6@gmail.com', 'Lucas França', 'Hi all,
I''m Lucas from Newcastle Upon Tyne. Started lessons in January - trying to get my hands and fingers to obey me... 😅', '[]', '2026-04-21 19:20:00+01'),
  ('group', 'ddbryson93@comcast.net', 'David A Bryson', 'Hello, everyone.  I am a 65 year old retired carpenter.  I haven''t played since I was 16. My first problem is that my fingers aren''t as flexible as they were 50 years ago.  I need to start with some exercises to make them work individually,  and to play notes with the same force.  If anyone has  any recommendations,  I would appreciate it.', '[]', '2026-04-21 20:44:00+01'),
  ('group', 'robert.m.ayres@outlook.com', 'Rob Ayres', 'Hi all! Born and bred in England but living in São Paulo, Brazil for past 14 years! I’m 44 and been self learning piano for a year now as have always wanted too. Played trumpet for 6/7 years in my youth so had some music reading knowledge already but Bass Clef proving harder than I imagined. Not progressing as quickly as I would like or thought I might but perhaps due to know bass line to which I can compare. Hand independence seems to be a struggle but enjoying the journey and do feel like I am getting better even if slow.', '[]', '2026-04-21 22:28:00+01'),
  ('group', 's.simzyk@gmail.com', 'Sarah S', 'Hi! I''m Sarah from the United States. I keep trying to learn piano on and off and I''m finally most of the way through a method book (Alfred''s). Figured this would be a great place to start branching out and finding pieces I actually enjoy playing, as some of the pieces in that book are hard to learn mostly because they sound genuinely awful lol.', '[]', '2026-04-21 23:43:00+01'),
  ('group', 'michaelpage05@hotmail.co.uk', 'Michael Page', '@Matthew Cawood May I make a suggestion? In the practice log section, I was wondering to keep it more or organised that instead of posting each session as a new post we have one post each and add days as comments on that post?', '[]', '2026-04-23 05:21:00+01'),
  ('group', 'jifupt@gmail.com', 'Joao Carvalho', 'Yesterday I wrote a very brief sentence, but I didn''t fully present myself. I''m a 39 y.o. guy from Portugal who decided to learn the piano at the beginning of last month. I looked into the recommendations for a beginner piano and ended up picking up a Yamaha P145 BT with the piano stand/3 pedal kit - I''m happy with my choice!
I watch some youtube videos to learn music theory and technique (and also for entertainment to be honest), while using Piano Marvel to have a more structured plan to follow and get some way to understand if I''m playing correctly (I find the feedback on the wrong timing to be quite helpful). I started having some wrist pain right after a couple of days of practicing, so I got online piano lessons every 2-3 weeks now, to correct my technique, mostly. I don''t mind going slow, but I really don''t want to get injured! :)
I''ve also purchased the first book of the Faber Piano Adventures, but to be honest I''ve barely used it. It took a while to get it delivered and I was already commmitted to Piano Marvel at that time... I pick it up randomly when I don''t feel like using a device with a screen (one of the reasons to pick up the piano was to stop using digital devices so much, so using an app was probably not the best of choices).
My goal at the piano is just being able to have fun with it along the journey. I know I''ll probably never play too challenging pieces, but I''m enjoying practicing and learning more about music. At the moment, I''m still learning a version of Ode to Joy that uses the left hand to get some harmony going - managing both hands has been a challenge. I might share it once I can play it without many mistakes, to try and get some feedback on the technique.', '[]', '2026-04-23 08:26:00+01'),
  ('group', 'michaelpage05@hotmail.co.uk', 'Michael Page', 'I have just put the Faber Piano Adventures 1 books in my wish list. As a lot of people are talking about them here. It my birthday soon so fingers crossed. 🤞', '[]', '2026-04-23 09:23:00+01'),
  ('group', 'robert.m.ayres@outlook.com', 'Rob Ayres', 'Hi @Matthew Cawood - i don`t appear to be able to access the Practice Hub and Resources. I send verification code to my registered email address but no code comes through. I saw in intro video this could happen for new members but still happening today.', '[]', '2026-04-23 09:33:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'PRACTICE HUB UPDATE: I''ve now added some more data to the practice hub...you can now see all the individual pieces and scales you''ve practiced. Including; how much time you''ve spent on each piece and how many sessions a particular scale has been included in. You can sort by most or least practiced and you can click the individual piece or scale to see the notes that were made in all sessions for that scale/piece. You can then click on each of those notes to see details of the full practice session that the scale/practice came from.', '[]', '2026-04-23 09:56:00+01'),
  ('group', 'steve@sonuslucis.com', 'Sonus Lucis', 'Hi Guys,
I''m originally from a place called Lewisham in South East London, UK although I''ve moved about a bit since then. I currently live near Hastings on the south coast.
I''ve been learning piano since June 2025 (with a brilliant local teacher) but I''ve had a lifelong interest in music.
The piece I''m working on at the moment is called Gentle Breeze.
I would say my level is mid to upper beginner.
My ultimate goal is to be able to pick up a piece of music and play it fairly competently from fresh but I really want to understand the structure of music with a view to writing instrumentals and songs for myself.
I have made some music with and without AI assistance that you can view on YouTube. You can find it at: https://www.youtube.com/@Sonus_Lucis/videos Older content on the channel is clips from games playing and lots of random stuff.', '[]', '2026-04-23 11:56:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Hey gang! A couple more updates for you:
In your pieces collection you can now see all of the information about the music and the sheet music link etc as well as in the database.
There are now youtube links to all of the pieces so you can hear what a piece sounds like before picking it. These were generated from the top results on youtube for the title of the piece and the composer, so there may be some of them that are not the best matches...but there is a report a problem button if you come across one of those and il swap it out for a better link.', '[]', '2026-04-23 13:27:00+01'),
  ('group', 'davidwhamilton79@gmail.com', 'David Hamilton', 'For those using Faber, can I ask where you are and what you''re working on? Im working on the ''Theme and Variations on the D minor scale'' at the end of unit 10 in book 2. The Battle of Jericho piece was lots of fun but the rhythm in Habanera im still finding a little tricky', '[]', '2026-04-23 18:00:00+01'),
  ('group', 'gnpedgar@yahoo.com', 'Norma Edgar', 'Hi everyone! I have watched Matt’s videos for a while- they have been incredibly helpful throughout my piano journey, and now I’m very happy to be part of The Practice Room.
I would say I am an intermediate student,  currently working on Debussy’s Arabesque No. 1, and couple of other smaller pieces. I have also completed some pop songs, and a jazz song, including chord progressions & related concepts. I worked through Faber’s book as well, some Hanon, and Alfred’s scales, chords and arpeggios book.  I’m really looking forward to learning from everyone here and being part of this community!', '[]', '2026-04-23 19:00:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Hey guys, I''ve changed the name of this chat so that it sounds less clinical.
When I was back at music college I worked on a piece for my technical studies in my 4th year which is a piece by a composer called Kapustin. He''s a 20th century Russian composer, but he created a series of preludes in a Jazz Style (which was surprising to me given he''s Russian) and they feel almost like a hybrid between Jazz/Classical. Anyway, I thought I''d share the piece/series of preludes with you because I think they are interesting to listen to. The piece I learned and am now brushing up again in my practice is no. 17 (https://www.youtube.com/watch?v=f9wxrI4fXDo&t=4s). Let me know what you think and if there''s any pieces you have worked on that are interesting.
pdfcoffee.com-24-preludes-in-jazz-style-op-53pdf (2).pdf
8.11 MB
YouTube
Nikolai Kapustin, 24 Preludes in jazz style op.53, No.17
Nikolai Kapustin, 24 Preludes in jazz style op.53, No.17', '[]', '2026-04-24 08:14:00+01'),
  ('group', 'steve@sonuslucis.com', 'Sonus Lucis', 'I''ve been on and off learning this version of American Beauty (originally called The Plastic Bag Theme) I''ve loved this piece for many years and knew of it before ever seeing the film. I love watching the composer, Thomas Newman, play it. He''s so natural. https://youtu.be/oDSYcNr-csY?si=iNyzco9gZXgsjiWz
YouTube
Thomas Newman Performs the Theme from "American Beauty"
Thomas Newman Performs the Theme from "American Beauty"', '[]', '2026-04-24 09:53:00+01'),
  ('group', 'lucaskinzo@hotmail.com', 'Luca Chiarella', 'Hi all, I live in London UK, 48yo and started learning in May 3 years ago. I''m a drummer and I feel this helps with timing and subdivisions of course.
I used a very popular online multi-instrument website method (don''t know if I''m allowed to say the name) to get me started.
I worked on a few Hanon exercises for tecnique and learned major and minor chords with inversions. I practiced these along songs on a popular guitar app.
I worked on a few classical pieces, my favorite genre: Fur Elise, Moonlight sonata first movement, Minuet in g major and minor, minuet in f major, Sonata k545, Pathetique sonata first movement, and a few others.
Currently working on Burgmuller opus100 in order.
By no means I play to perfection. I just enjoy the music.
Goals for this year hopefully is learn to boogie woogie and slow jazz.
Hope Matt can help in this matter 🙂
What I really need is structured practice, as for the moment I''m just sitting at the piano without a real plan on what to do.
I have the luxury of being able to dedicate a few hours a day on the instrument, I just need the right directions.
Nice to be here 👍🏻', '[]', '2026-04-24 16:07:00+01'),
  ('group', 'csikzsuzsi@gmail.com', 'Zsuzsa Csik', 'Hi, sorry I''m a bit late to the party but the week was busy!
I''m from Hungary but currently living in Brazil. I learned to play the piano between the ages of 6 and 12, when adolescence took over and I quit. I regretted it soon after, yet it took 27 years to pick it up again. I finally got a Roland FP-30x in late January this year, and I love starting over.
Interestingly, I don''t know how, but 6-year-old me made a weird deal with my piano teacher, so I hardly learned any music theory beyond the bare minimum to read the notes. No scales, no chords, nothing like that. Now I''m catching up with all that.
I don''t have any particular goals other than having fun and learning nice pieces. I started with some recommendations, I think from Matt''s videos (Menuet in F, Menuet in G), and now I''m trying the Clementi Sonatina. Soon, I will gather my courage and record something to get my first feedback, as I don''t have a teacher.
I''m super happy to be part of this community and looking forward to all the exchanges and learning!', '[]', '2026-04-24 17:16:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Here''s some data for you guys! I thought you might like to see what''s been happening between everyone collectively in the Practice Hub over just the last 2 days.
Attachment image', '[]', '2026-04-24 18:31:00+01'),
  ('group', 'matthew@matthewcawood.com', 'Matthew Cawood', 'Hello team, it’s the first live Q&A on Monday. I will of course answer any live questions, but if you have anything specific you want me to answer or a topic you’d like me to go through, feel free to respond to this or leave it as a comment on the Q&A itself in the Live Q&A feed.
Il probably pick a topic to talk through as well based on earlier questions and the questions in the “Ask Matt Anything” 😊', '[]', '2026-04-25 07:46:00+01'),
  ('group', 'danielduordoe@yahoo.co.uk', 'Daniel Duordoe', 'Hi Matt, would you be open to mixing up the days and times for our live Q&A? It could really help members with different work/life schedules and others in different time zones join in more easily.', '[]', '2026-04-25 09:00:00+01');

-- Verify count
SELECT COUNT(*) AS message_count FROM community_messages WHERE chat_id = 'group';