-- ──────────────────────────────────────────────────────────────────────────────
-- Seed: Music Glossary
-- Categories: Tempo, Dynamics, Articulation, Ornaments, Expression, Form,
--             Rhythm, Pitch, Harmony, Notation
-- Rules: definitions are self-contained (no cross-references to other terms),
--        no absolute superlatives (no "the slowest/fastest/softest/loudest"),
--        symbol_html set for every term that has a visual symbol in sheet music
-- ──────────────────────────────────────────────────────────────────────────────

INSERT INTO glossary (term, definition, category, origin, symbol_html) VALUES

-- ── TEMPO ────────────────────────────────────────────────────────────────────
-- Tempo markings are written as text in scores, not symbols
('Larghissimo',   'Extremely slow and broad — typically below 24 beats per minute.',                                                                             'Tempo', 'Italian', NULL),
('Grave',         'Slow and solemn in character, conveying a sense of weight and seriousness.',                                                                  'Tempo', 'Italian', NULL),
('Largo',         'Very slow and broad, approximately 40–60 beats per minute. Conveys a wide, expansive feel.',                                                  'Tempo', 'Italian', NULL),
('Larghetto',     'Slow but with a slightly more flowing quality than the broadest tempos. Approximately 60–66 beats per minute.',                               'Tempo', 'Italian', NULL),
('Adagio',        'Slow and stately, approximately 60–76 beats per minute.',                                                                                     'Tempo', 'Italian', NULL),
('Adagietto',     'Unhurried but gently flowing — slightly more animated than a fully slow tempo. Approximately 70–80 beats per minute.',                        'Tempo', 'Italian', NULL),
('Andante',       'At a calm, walking pace, approximately 76–108 beats per minute. Literally "going" in Italian.',                                               'Tempo', 'Italian', NULL),
('Andantino',     'At a gentle, slightly varied walking pace. Historically interpreted differently by different composers.',                                      'Tempo', 'Italian', NULL),
('Moderato',      'At a moderate pace, approximately 108–120 beats per minute — neither fast nor slow.',                                                         'Tempo', 'Italian', NULL),
('Allegretto',    'Moderately fast and light in character, approximately 112–120 beats per minute.',                                                             'Tempo', 'Italian', NULL),
('Allegro',       'Fast and lively, approximately 120–168 beats per minute.',                                                                                    'Tempo', 'Italian', NULL),
('Vivace',        'Lively and fast, approximately 168–176 beats per minute. Bright and energetic in character.',                                                 'Tempo', 'Italian', NULL),
('Vivacissimo',   'Very fast and highly animated — an especially intense, energetic pace.',                                                                      'Tempo', 'Italian', NULL),
('Presto',        'Very fast, approximately 168–200 beats per minute.',                                                                                          'Tempo', 'Italian', NULL),
('Prestissimo',   'Extremely fast — as fast as possible, typically above 200 beats per minute.',                                                                 'Tempo', 'Italian', NULL),
('Accelerando',   'Gradually becoming faster. Abbreviated accel.',                                                                                               'Tempo', 'Italian', NULL),
('Ritardando',    'Gradually slowing down. Abbreviated rit. or ritard.',                                                                                         'Tempo', 'Italian', NULL),
('Rallentando',   'Gradually slowing down over a passage. Abbreviated rall.',                                                                                    'Tempo', 'Italian', NULL),
('Ritenuto',      'Held back — an immediate slowing of the tempo rather than a gradual reduction in speed. Abbreviated riten.',                                  'Tempo', 'Italian', NULL),
('Rubato',        'Flexible tempo — the performer takes rhythmic freedom, pushing and pulling the speed expressively for musical effect.',                        'Tempo', 'Italian', NULL),
('A tempo',       'Return to the original speed of the piece after a passage where the tempo has changed.',                                                      'Tempo', 'Italian', NULL),
('Tempo giusto',  'In exact, strict time — no flexibility or rhythmic freedom.',                                                                                 'Tempo', 'Italian', NULL),
('Meno mosso',    'Less motion — at a slower speed than the preceding passage.',                                                                                 'Tempo', 'Italian', NULL),
('Più mosso',     'More motion — at a faster speed than the preceding passage.',                                                                                 'Tempo', 'Italian', NULL),
('Poco a poco',   'Little by little — indicates a change that happens gradually, e.g. getting louder little by little.',                                         'Tempo', 'Italian', NULL),
('Subito',        'Suddenly — indicates an immediate change, e.g. suddenly becoming quiet.',                                                                     'Tempo', 'Italian', NULL),

-- ── DYNAMICS ─────────────────────────────────────────────────────────────────
('Pianississimo', 'Extremely soft. Abbreviated ppp.',                                                                                                            'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">ppp</em>'),
('Pianissimo',    'Very soft. Abbreviated pp.',                                                                                                                  'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">pp</em>'),
('Piano',         'Soft. Abbreviated p.',                                                                                                                        'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">p</em>'),
('Mezzo-piano',   'Moderately soft — between soft and medium volume. Abbreviated mp.',                                                                           'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">mp</em>'),
('Mezzo-forte',   'Moderately loud — between medium and loud volume. Abbreviated mf.',                                                                           'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">mf</em>'),
('Forte',         'Loud. Abbreviated f.',                                                                                                                        'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">f</em>'),
('Fortissimo',    'Very loud. Abbreviated ff.',                                                                                                                  'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">ff</em>'),
('Fortississimo', 'Extremely loud. Abbreviated fff.',                                                                                                            'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">fff</em>'),
('Sforzando',     'A sudden, strong accent on a single note or chord. Abbreviated sfz or sf.',                                                                   'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">sfz</em>'),
('Forte-piano',   'Loud immediately followed by soft — an abrupt dynamic contrast on a single note or chord. Abbreviated fp.',                                   'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">fp</em>'),
('Crescendo',     'Gradually becoming louder. Abbreviated cresc. Shown in music as an opening wedge (hairpin) — narrow on the left, wide on the right.',         'Dynamics', 'Italian',
 '<svg width="36" height="20" viewBox="0 0 36 20" style="vertical-align:middle"><line x1="2" y1="10" x2="34" y2="3" stroke="currentColor" stroke-width="1.5" fill="none"/><line x1="2" y1="10" x2="34" y2="17" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Decrescendo',   'Gradually becoming softer. Abbreviated decresc. Shown in music as a closing wedge (hairpin) — wide on the left, narrow on the right.',        'Dynamics', 'Italian',
 '<svg width="36" height="20" viewBox="0 0 36 20" style="vertical-align:middle"><line x1="2" y1="3" x2="34" y2="10" stroke="currentColor" stroke-width="1.5" fill="none"/><line x1="2" y1="17" x2="34" y2="10" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Diminuendo',    'Gradually becoming softer. Abbreviated dim. Used interchangeably with decrescendo.',                                                          'Dynamics', 'Italian',
 '<svg width="36" height="20" viewBox="0 0 36 20" style="vertical-align:middle"><line x1="2" y1="3" x2="34" y2="10" stroke="currentColor" stroke-width="1.5" fill="none"/><line x1="2" y1="17" x2="34" y2="10" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Niente',        'Nothing — used to indicate fading to complete silence. Often written as "al niente" (to nothing) at the end of a passage getting softer.',    'Dynamics', 'Italian', '<em style="font-family:serif;font-style:italic;font-weight:700;font-size:1.1em">n</em>'),

-- ── ARTICULATION ─────────────────────────────────────────────────────────────
('Legato',        'Smooth and connected — notes flow into each other without any gap. Indicated by a curved line drawn over or under a group of notes.',
 'Articulation', 'Italian',
 '<svg width="38" height="14" viewBox="0 0 38 14" style="vertical-align:middle"><circle cx="6" cy="8" r="3.5" fill="currentColor"/><circle cx="19" cy="8" r="3.5" fill="currentColor"/><circle cx="32" cy="8" r="3.5" fill="currentColor"/><path d="M3,5 Q19,0 35,5" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Staccato',      'Short and detached — each note is clipped shorter than its written value, creating a small silence before the next note. Shown by a dot above or below the note head.',
 'Articulation', 'Italian',
 '<svg width="28" height="20" viewBox="0 0 28 20" style="vertical-align:middle"><circle cx="8" cy="14" r="3.5" fill="currentColor"/><circle cx="8" cy="4" r="2.5" fill="currentColor"/><circle cx="20" cy="14" r="3.5" fill="currentColor"/><circle cx="20" cy="4" r="2.5" fill="currentColor"/></svg>'),
('Tenuto',        'Hold the note for its full written duration, sometimes with a slight emphasis. Shown by a short horizontal line above or below the note.',
 'Articulation', 'Italian',
 '<svg width="28" height="20" viewBox="0 0 28 20" style="vertical-align:middle"><circle cx="8" cy="14" r="3.5" fill="currentColor"/><line x1="3" y1="5" x2="13" y2="5" stroke="currentColor" stroke-width="2"/><circle cx="20" cy="14" r="3.5" fill="currentColor"/><line x1="15" y1="5" x2="25" y2="5" stroke="currentColor" stroke-width="2"/></svg>'),
('Accent',        'Emphasise a note — play it with more weight or volume than the surrounding notes. Shown by a > symbol above or below the note.',
 'Articulation', 'Italian',
 '<svg width="20" height="16" viewBox="0 0 20 16" style="vertical-align:middle"><line x1="2" y1="8" x2="18" y2="2" stroke="currentColor" stroke-width="1.5"/><line x1="2" y1="8" x2="18" y2="14" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Marcato',       'Strongly marked — played with considerable emphasis and weight. Shown by a ^ symbol above the note.',
 'Articulation', 'Italian',
 '<svg width="18" height="14" viewBox="0 0 18 14" style="vertical-align:middle"><line x1="2" y1="13" x2="9" y2="2" stroke="currentColor" stroke-width="1.5"/><line x1="9" y1="2" x2="16" y2="13" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Portato',       'Semi-detached — notes are gently separated but not as abruptly clipped as a fully detached touch. Shown by a curved line with dots beneath each note.',
 'Articulation', 'Italian',
 '<svg width="38" height="18" viewBox="0 0 38 18" style="vertical-align:middle"><circle cx="6" cy="10" r="3.5" fill="currentColor"/><circle cx="19" cy="10" r="3.5" fill="currentColor"/><circle cx="32" cy="10" r="3.5" fill="currentColor"/><path d="M3,7 Q19,2 35,7" stroke="currentColor" stroke-width="1.5" fill="none"/><circle cx="6" cy="16" r="2" fill="currentColor"/><circle cx="19" cy="16" r="2" fill="currentColor"/><circle cx="32" cy="16" r="2" fill="currentColor"/></svg>'),
('Staccatissimo', 'Very short and sharply detached — notes are clipped to the briefest possible duration. Shown by a small wedge above or below the note.',
 'Articulation', 'Italian',
 '<svg width="28" height="22" viewBox="0 0 28 22" style="vertical-align:middle"><circle cx="8" cy="16" r="3.5" fill="currentColor"/><polygon points="8,2 5,8 11,8" fill="currentColor"/><circle cx="20" cy="16" r="3.5" fill="currentColor"/><polygon points="20,2 17,8 23,8" fill="currentColor"/></svg>'),
('Slur',          'A curved line connecting two or more notes of different pitches, indicating they should be played smoothly and without separation.',
 'Articulation', NULL,
 '<svg width="40" height="16" viewBox="0 0 40 16" style="vertical-align:middle"><circle cx="5" cy="11" r="3.5" fill="currentColor"/><circle cx="20" cy="11" r="3.5" fill="currentColor"/><circle cx="35" cy="11" r="3.5" fill="currentColor"/><path d="M3,8 Q20,0 37,8" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Tie',           'A curved line connecting two notes of the same pitch, combining their durations into one sustained sound.',
 'Articulation', NULL,
 '<svg width="36" height="14" viewBox="0 0 36 14" style="vertical-align:middle"><circle cx="5" cy="9" r="3.5" fill="currentColor"/><circle cx="31" cy="9" r="3.5" fill="currentColor"/><path d="M5,7 Q18,0 31,7" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Fermata',       'Hold the note (or rest) longer than its written value — the exact length is left to the performer or conductor. Also called a pause.',
 'Articulation', 'Italian', '<span style="font-size:1.6em">𝄐</span>'),

-- ── ORNAMENTS ────────────────────────────────────────────────────────────────
('Trill',         'Rapid alternation between the written note and the note one step above it. Abbreviated tr, often followed by a wavy line.',
 'Ornaments', NULL,
 '<span style="font-family:serif;font-style:italic;font-weight:bold;font-size:1.05em">tr</span><svg width="28" height="12" viewBox="0 0 28 12" style="vertical-align:middle"><path d="M0,6 Q3.5,0 7,6 Q10.5,12 14,6 Q17.5,0 21,6 Q24.5,12 28,6" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Mordent',       'A quick alternation between the written note and the note one step below it, returning immediately to the written note. Shown by a wavy line with a vertical stroke through it.',
 'Ornaments', NULL,
 '<svg width="28" height="16" viewBox="0 0 28 16" style="vertical-align:middle"><path d="M2,8 Q6,2 10,8 Q14,14 18,8 Q22,2 26,8" stroke="currentColor" stroke-width="1.5" fill="none"/><line x1="10" y1="1" x2="10" y2="15" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Inverted Mordent', 'A quick alternation between the written note and the note one step above it, returning immediately to the written note. Also called an upper mordent or pralltriller.',
 'Ornaments', NULL,
 '<svg width="28" height="16" viewBox="0 0 28 16" style="vertical-align:middle"><path d="M2,8 Q6,2 10,8 Q14,14 18,8 Q22,2 26,8" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Turn',          'A four-note ornament that moves from the note above the written pitch, down through it to the note below, then back up to the written pitch.',
 'Ornaments', NULL,
 '<svg width="28" height="18" viewBox="0 0 28 18" style="vertical-align:middle"><path d="M4,6 Q8,1 13,5 Q18,10 22,7 Q26,4 24,12 Q22,16 18,14" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Appoggiatura',  'A small grace note that leans into and borrows time from the main note that follows it, played on the beat. Adds expressive weight and a sense of longing.',
 'Ornaments', 'Italian',
 '<svg width="30" height="26" viewBox="0 0 30 26" style="vertical-align:middle"><ellipse cx="7" cy="20" rx="5" ry="3.5" fill="currentColor" transform="rotate(-15,7,20)"/><line x1="11" y1="19" x2="11" y2="8" stroke="currentColor" stroke-width="1.2"/><ellipse cx="22" cy="20" rx="6" ry="4" fill="currentColor" transform="rotate(-15,22,20)"/><line x1="27" y1="19" x2="27" y2="4" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Acciaccatura',  'A crushed grace note — played as quickly as possible just before the main note. Shown as a small note with a stroke through its stem.',
 'Ornaments', 'Italian',
 '<svg width="30" height="26" viewBox="0 0 30 26" style="vertical-align:middle"><ellipse cx="7" cy="20" rx="5" ry="3.5" fill="currentColor" transform="rotate(-15,7,20)"/><line x1="11" y1="19" x2="11" y2="8" stroke="currentColor" stroke-width="1.2"/><line x1="5" y1="16" x2="14" y2="9" stroke="currentColor" stroke-width="1.2"/><ellipse cx="22" cy="20" rx="6" ry="4" fill="currentColor" transform="rotate(-15,22,20)"/><line x1="27" y1="19" x2="27" y2="4" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Glissando',     'A continuous slide from one pitch to another, passing through all the pitches in between.',
 'Ornaments', 'Italian',
 '<svg width="36" height="22" viewBox="0 0 36 22" style="vertical-align:middle"><circle cx="4" cy="18" r="3.5" fill="currentColor"/><line x1="6" y1="16" x2="30" y2="5" stroke="currentColor" stroke-width="1.5" stroke-dasharray="3,2"/><circle cx="32" cy="4" r="3.5" fill="currentColor"/></svg>'),
('Tremolo',       'Rapid repetition of a single note, or rapid alternation between two notes, creating a shimmering or agitated effect.',
 'Ornaments', 'Italian',
 '<svg width="26" height="22" viewBox="0 0 26 22" style="vertical-align:middle"><ellipse cx="8" cy="17" rx="6" ry="4" fill="currentColor" transform="rotate(-15,8,17)"/><line x1="13" y1="15" x2="13" y2="2" stroke="currentColor" stroke-width="1.5"/><line x1="4" y1="6" x2="22" y2="2" stroke="currentColor" stroke-width="1.5"/><line x1="4" y1="10" x2="22" y2="6" stroke="currentColor" stroke-width="1.5"/><line x1="4" y1="14" x2="22" y2="10" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Vibrato',       'A slight, rapid fluctuation in pitch used to add warmth and expressiveness to a sustained note.',
 'Ornaments', 'Italian', NULL),
('Arpeggio',      'The notes of a chord played in quick succession from the bottom upward rather than all at once — sometimes called a broken chord. Shown by a vertical wavy line before the chord.',
 'Ornaments', 'Italian',
 '<svg width="14" height="36" viewBox="0 0 14 36" style="vertical-align:middle"><path d="M7,34 Q12,29 5,24 Q11,19 5,14 Q11,9 5,4" stroke="currentColor" stroke-width="1.5" fill="none"/><polygon points="5,2 2,8 8,8" fill="currentColor"/></svg>'),

-- ── EXPRESSION ───────────────────────────────────────────────────────────────
-- Expression marks are written as Italian text in scores — no dedicated symbols
('Cantabile',     'In a singing style — smooth, lyrical and expressive, like a human voice sustaining a melody.',                                                 'Expression', 'Italian', NULL),
('Dolce',         'Sweetly — soft and gentle in tone and character.',                                                                                             'Expression', 'Italian', NULL),
('Espressivo',    'Expressively — with feeling and personal emotion. Abbreviated espress.',                                                                       'Expression', 'Italian', NULL),
('Grazioso',      'Gracefully — elegant and light in character.',                                                                                                 'Expression', 'Italian', NULL),
('Maestoso',      'Majestically — dignified, stately and broad.',                                                                                                 'Expression', 'Italian', NULL),
('Misterioso',    'Mysteriously — with a sense of the unknown or the hidden.',                                                                                    'Expression', 'Italian', NULL),
('Agitato',       'Agitated — restless, hurried and unsettled in character.',                                                                                     'Expression', 'Italian', NULL),
('Animato',       'Animated — lively and spirited.',                                                                                                              'Expression', 'Italian', NULL),
('Brillante',     'Brilliantly — with sparkle and flair.',                                                                                                        'Expression', 'Italian', NULL),
('Con brio',      'With vigour — energetic and spirited.',                                                                                                        'Expression', 'Italian', NULL),
('Con fuoco',     'With fire — passionate and intense.',                                                                                                          'Expression', 'Italian', NULL),
('Con moto',      'With motion — keep a sense of forward movement; do not let the music become static.',                                                          'Expression', 'Italian', NULL),
('Giocoso',       'Playful and humorous.',                                                                                                                        'Expression', 'Italian', NULL),
('Grandioso',     'Grandly — broad, majestic and impressive.',                                                                                                    'Expression', 'Italian', NULL),
('Leggiero',      'Lightly — delicate, nimble and airy in touch.',                                                                                                'Expression', 'Italian', NULL),
('Pesante',       'Heavily — with deliberate weight.',                                                                                                            'Expression', 'Italian', NULL),
('Scherzando',    'Playfully — light-hearted and joking in character.',                                                                                           'Expression', 'Italian', NULL),
('Semplice',      'Simply — in a plain, unaffected style without decoration or exaggeration.',                                                                    'Expression', 'Italian', NULL),
('Tranquillo',    'Calmly — peaceful and undisturbed.',                                                                                                           'Expression', 'Italian', NULL),
('Vigoroso',      'Vigorously — with energy and strength.',                                                                                                       'Expression', 'Italian', NULL),
('Sostenuto',     'Sustained — hold notes for their full value with a sense of breadth and continuity.',                                                          'Expression', 'Italian', NULL),
('Appassionato',  'Passionately — with intense emotion.',                                                                                                         'Expression', 'Italian', NULL),
('Furioso',       'Furiously — wild and intense in character.',                                                                                                   'Expression', 'Italian', NULL),
('Lamentoso',     'Mournfully — with sadness and grief.',                                                                                                         'Expression', 'Italian', NULL),
('Mesto',         'Sad or mournful in character.',                                                                                                                'Expression', 'Italian', NULL),

-- ── FORM ─────────────────────────────────────────────────────────────────────
-- Form terms have no dedicated symbols except Coda
('Binary form',     'A two-part musical structure (A–B), where each section may be repeated.',                                                                   'Form', NULL, NULL),
('Ternary form',    'A three-part musical structure (A–B–A) — an opening section is followed by a contrasting middle section, after which the opening section returns.',  'Form', NULL, NULL),
('Rondo form',      'A structure in which a main theme returns repeatedly between contrasting sections: A–B–A–C–A or similar. The returning theme acts as a refrain.',  'Form', NULL, NULL),
('Sonata form',     'A large-scale structure with three main sections: an Exposition (where themes are introduced), a Development (where themes are explored and transformed), and a Recapitulation (where themes return).',  'Form', NULL, NULL),
('Theme and variations', 'A theme is stated and then repeated multiple times, each time with changes — in melody, rhythm, harmony, texture, or character.',       'Form', NULL, NULL),
('Canon',           'A technique where a melody is introduced by one voice and then imitated exactly by one or more other voices, each entering a short time later — creating overlapping layers of the same tune.',  'Form', NULL, NULL),
('Fugue',           'A composition built on a short theme (the subject) that is stated alone, then imitated in overlapping entries by additional voices, all woven together throughout the piece.',  'Form', NULL, NULL),
('Through-composed', 'A piece in which new music is written for each section throughout — no large sections repeat.',                                             'Form', NULL, NULL),
('Coda',            'A concluding passage that brings a piece or section to a close.',                                                                            'Form', 'Italian', '<span style="font-size:1.4em">𝄌</span>'),
('Exposition',      'The opening section of a movement where the main musical themes are first introduced and established.',                                      'Form', NULL, NULL),
('Development',     'A section where earlier musical ideas are fragmented, varied and taken through different moods and keys — creating tension and exploration.', 'Form', NULL, NULL),
('Recapitulation',  'A section where the main themes of a movement return, typically bringing a sense of resolution and homecoming.',                             'Form', NULL, NULL),
('Prelude',         'An introductory piece, or a short self-contained character piece.',                                                                          'Form', NULL, NULL),
('Nocturne',        'A lyrical, contemplative character piece, typically written for piano. Evokes the mood of the night.',                                       'Form', NULL, NULL),
('Étude',           'A study piece designed to develop a specific technical skill. The word is French for "study".',                                              'Form', 'French', NULL),
('Intermezzo',      'A short character piece, or a movement that falls between larger sections of a work.',                                                       'Form', 'Italian', NULL),
('Impromptu',       'A character piece that gives the impression of spontaneous improvisation.',                                                                  'Form', NULL, NULL),
('Ballade',         'A dramatic narrative piece, typically written as a large-scale single movement.',                                                            'Form', NULL, NULL),
('Scherzo',         'A lively, playful movement or piece, usually in triple time. Literally "joke" in Italian.',                                                  'Form', 'Italian', NULL),
('Minuet',          'An elegant triple-time dance at a moderate pace, common in Baroque and Classical era compositions.',                                         'Form', NULL, NULL),
('Suite',           'A collection of contrasting movements, often based on dances, grouped together as a single work.',                                           'Form', NULL, NULL),
('Concerto',        'A work for one or more solo instruments accompanied by an orchestra, typically in three movements.',                                         'Form', 'Italian', NULL),
('Sonata',          'A multi-movement work for one or two instruments. The term also refers to the structural conventions commonly used within such works.',       'Form', 'Italian', NULL),

-- ── RHYTHM ───────────────────────────────────────────────────────────────────
('Time signature',  'Two numbers stacked at the start of a piece: the top number indicates how many beats are in each bar; the bottom number indicates what kind of note equals one beat.',
 'Rhythm', NULL,
 '<span style="display:inline-flex;flex-direction:column;align-items:center;line-height:1.1;font-weight:bold;font-size:1.2em;font-family:serif;gap:0"><span>4</span><span>4</span></span>'),
('Common time',     'Four beats per bar, where each beat is a quarter note. One of the most frequently used time signatures. Often notated with a C symbol.',
 'Rhythm', NULL, '<span style="font-size:1.5em">𝄴</span>'),
('Cut time',        'Two beats per bar, where each beat is a half note. Music in cut time moves at a broader, two-in-a-bar pulse. Also called alla breve.',
 'Rhythm', NULL, '<span style="font-size:1.5em">𝄵</span>'),
('Syncopation',     'Emphasis placed on a beat that is normally weak, or between beats — creates a sense of rhythmic surprise or groove.',                         'Rhythm', NULL, NULL),
('Triplet',         'Three notes played evenly in the time normally occupied by two, indicated by a bracket and the number 3.',
 'Rhythm', NULL,
 '<svg width="38" height="20" viewBox="0 0 38 20" style="vertical-align:middle"><circle cx="6" cy="15" r="3.5" fill="currentColor"/><circle cx="19" cy="15" r="3.5" fill="currentColor"/><circle cx="32" cy="15" r="3.5" fill="currentColor"/><line x1="6" y1="11" x2="6" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="6" y1="6" x2="32" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="32" y1="6" x2="32" y2="11" stroke="currentColor" stroke-width="1.2"/><text x="19" y="5" text-anchor="middle" font-size="9" fill="currentColor" font-family="serif">3</text></svg>'),
('Duplet',          'Two notes played evenly across the time normally occupied by three, indicated by a bracket and the number 2.',
 'Rhythm', NULL,
 '<svg width="28" height="20" viewBox="0 0 28 20" style="vertical-align:middle"><circle cx="7" cy="15" r="3.5" fill="currentColor"/><circle cx="21" cy="15" r="3.5" fill="currentColor"/><line x1="7" y1="11" x2="7" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="7" y1="6" x2="21" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="21" y1="6" x2="21" y2="11" stroke="currentColor" stroke-width="1.2"/><text x="14" y="5" text-anchor="middle" font-size="9" fill="currentColor" font-family="serif">2</text></svg>'),
('Hemiola',         'A rhythmic device where the music shifts between a feeling of two groups of three beats and three groups of two beats — creating a sense of rhythmic ambiguity.',  'Rhythm', NULL, NULL),
('Anacrusis',       'One or more notes before the first full bar of a piece — also called an upbeat or pick-up.',                                                 'Rhythm', NULL, NULL),
('Downbeat',        'The first beat of a bar — typically the strongest, most emphasised beat.',                                                                   'Rhythm', NULL, NULL),
('Upbeat',          'A relatively weak beat that leads into a stronger beat, or the final beat of a bar that propels into the next bar.',                         'Rhythm', NULL, NULL),
('Polyrhythm',      'Two or more contrasting rhythmic patterns played simultaneously, e.g. three notes against two.',                                             'Rhythm', NULL, NULL),
('Augmentation',    'A compositional device where a musical theme is repeated with all its note values lengthened — typically doubled in duration.',              'Rhythm', NULL, NULL),
('Diminution',      'A compositional device where a musical theme is repeated with all its note values shortened — typically halved in duration.',                'Rhythm', NULL, NULL),
('Ostinato',        'A short rhythmic or melodic pattern repeated persistently throughout a section or entire piece.',                                             'Rhythm', 'Italian', NULL),
('Compound time',   'A time signature where each beat naturally divides into three equal parts. Examples include 6/8, 9/8 and 12/8.',
 'Rhythm', NULL,
 '<span style="display:inline-flex;flex-direction:column;align-items:center;line-height:1.1;font-weight:bold;font-size:1.2em;font-family:serif;gap:0"><span>6</span><span>8</span></span>'),
('Simple time',     'A time signature where each beat naturally divides into two equal parts. Examples include 2/4, 3/4 and 4/4.',
 'Rhythm', NULL,
 '<span style="display:inline-flex;flex-direction:column;align-items:center;line-height:1.1;font-weight:bold;font-size:1.2em;font-family:serif;gap:0"><span>4</span><span>4</span></span>'),

-- ── PITCH ────────────────────────────────────────────────────────────────────
('Sharp',           'Raises a note by one half-step (the smallest pitch distance in standard Western music). Shown by the ♯ symbol.',                            'Pitch', NULL, '<span style="font-size:1.4em">♯</span>'),
('Flat',            'Lowers a note by one half-step (the smallest pitch distance in standard Western music). Shown by the ♭ symbol.',                            'Pitch', NULL, '<span style="font-size:1.4em">♭</span>'),
('Natural',         'Cancels a previous sharp or flat, returning the note to its unaltered pitch. Shown by the ♮ symbol.',                                       'Pitch', NULL, '<span style="font-size:1.4em">♮</span>'),
('Double sharp',    'Raises a note by two half-steps (a whole step). Shown by the 𝄪 symbol.',                                                                   'Pitch', NULL, '<span style="font-size:1.4em">𝄪</span>'),
('Double flat',     'Lowers a note by two half-steps (a whole step). Shown by the 𝄫 symbol.',                                                                   'Pitch', NULL, '<span style="font-size:1.4em">𝄫</span>'),
('Semitone',        'The smallest distance between two pitches in standard Western music — equivalent to moving one key to the next on a piano, whether white or black. Also called a half step.', 'Pitch', NULL, NULL),
('Tone',            'A pitch distance of two half-steps — also called a whole step or whole tone. The distance from C to D, for example.',                       'Pitch', NULL, NULL),
('Octave',          'A pitch interval where the higher note vibrates at exactly double the frequency of the lower. Both notes share the same letter name, e.g. C to the next C.',  'Pitch', NULL, NULL),
('Enharmonic',      'Two notes that sound identical but are written differently, e.g. C♯ and D♭ are the same key on the piano but named differently depending on the key.',       'Pitch', NULL, NULL),
('Accidental',      'A sharp, flat, or natural sign placed before a note to temporarily alter its pitch within a bar, outside of what the key signature already specifies.',       'Pitch', NULL, '<span style="font-size:1.2em">♯ ♭ ♮</span>'),
('Ledger lines',    'Short lines added above or below the five-line staff to notate pitches that fall outside its range.',
 'Pitch', NULL,
 '<svg width="36" height="28" viewBox="0 0 36 28" style="vertical-align:middle"><line x1="2" y1="8" x2="34" y2="8" stroke="currentColor" stroke-width="1"/><line x1="2" y1="14" x2="34" y2="14" stroke="currentColor" stroke-width="1"/><line x1="2" y1="20" x2="34" y2="20" stroke="currentColor" stroke-width="1"/><line x1="10" y1="26" x2="26" y2="26" stroke="currentColor" stroke-width="1.5"/><ellipse cx="18" cy="26" rx="7" ry="4.5" fill="currentColor" transform="rotate(-15,18,26)"/></svg>'),
('Ottava',          'Play one octave higher than written. Shown as 8va above the passage, ending with a dotted line.',                                           'Pitch', 'Italian', '<em style="font-style:italic;font-size:1.0em">8va ·····</em>'),
('Ottava bassa',    'Play one octave lower than written. Shown as 8vb or 8ba below the passage.',                                                                'Pitch', 'Italian', '<em style="font-style:italic;font-size:1.0em">8vb ·····</em>'),
('Loco',            'Return to playing at the written pitch after a passage that was played at a different octave.',                                              'Pitch', 'Italian', NULL),
('Register',        'The range of pitches in a particular part of an instrument or voice — for example, the low, middle or upper range.',                         'Pitch', NULL, NULL),

-- ── HARMONY ──────────────────────────────────────────────────────────────────
-- Harmony concepts are described in text in scores — no dedicated standalone symbols
('Major scale',     'An ordered sequence of eight notes with a bright, settled character. Built using the interval pattern: whole, whole, half, whole, whole, whole, half step.',  'Harmony', NULL, NULL),
('Minor scale',     'An ordered sequence of eight notes with a darker, more serious character. The natural minor uses the pattern: whole, half, whole, whole, half, whole, whole step.',  'Harmony', NULL, NULL),
('Chromatic scale', 'A scale made entirely of half-steps — twelve pitches spanning one octave, using every adjacent note.',                                      'Harmony', NULL, NULL),
('Pentatonic scale','A scale of five notes per octave. The major pentatonic version has a bright, open sound and is common in folk and popular music worldwide.', 'Harmony', NULL, NULL),
('Whole tone scale','A scale built entirely of whole steps — six notes per octave. Creates a dreamy, ambiguous sound with no strong sense of a home note.',       'Harmony', NULL, NULL),
('Interval',        'The distance in pitch between two notes, measured and named according to how many steps apart they are, e.g. a third, a fifth, an octave.', 'Harmony', NULL, NULL),
('Triad',           'A three-note chord built by stacking two intervals of a third: a root note, a note a third above it, and a note a fifth above the root.',   'Harmony', NULL, NULL),
('Seventh chord',   'A four-note chord formed by adding a note a seventh above the root to a basic three-note chord.',                                           'Harmony', NULL, NULL),
('Tonic',           'The first note of a scale — the home note and key centre of a piece. Music built around the tonic tends to feel settled and resolved.',     'Harmony', NULL, NULL),
('Dominant',        'The fifth note of a scale. Chords built on this note create tension that typically pulls toward the home note of the key.',                  'Harmony', NULL, NULL),
('Subdominant',     'The fourth note of a scale. Chords built on this note create a sense of departure or openness away from the home key.',                     'Harmony', NULL, NULL),
('Leading note',    'The seventh note of a scale — one half-step below the home note of the key. Creates a strong upward pull toward resolution.',               'Harmony', NULL, NULL),
('Modulation',      'Moving from one key to another within a piece of music.',                                                                                   'Harmony', NULL, NULL),
('Transposition',   'Moving a melody or passage to a different pitch level, keeping all the intervals exactly the same.',                                         'Harmony', NULL, NULL),
('Perfect cadence', 'A chord progression that moves from the chord built on the fifth note of the scale to the chord built on the home note — creates a strong sense of finality, like a musical full stop.',  'Harmony', NULL, NULL),
('Plagal cadence',  'A chord progression that moves from the chord built on the fourth note of the scale to the chord built on the home note. Known as the "Amen" cadence, common in hymns.',  'Harmony', NULL, NULL),
('Imperfect cadence', 'A cadence that ends on the chord built on the fifth note of the scale — feels unresolved, like a musical question.',                      'Harmony', NULL, NULL),
('Interrupted cadence', 'A cadence where the music appears to be heading toward the home chord but unexpectedly lands on a different chord instead — creates surprise.',  'Harmony', NULL, NULL),
('Diatonic',        'Using only the notes that belong to the current key, without any additions.',                                                                'Harmony', NULL, NULL),
('Chromatic',       'Using notes from outside the current key — adding colour, tension or a heightened sense of expression.',                                     'Harmony', NULL, NULL),
('Consonance',      'A combination of notes that sounds stable and pleasing — creates a sense of rest.',                                                          'Harmony', NULL, NULL),
('Dissonance',      'A combination of notes that sounds tense or unstable — typically wants to move toward a more settled sound.',                                'Harmony', NULL, NULL),
('Counterpoint',    'Two or more independent melodic lines played at the same time, each with its own rhythm and contour, yet fitting together harmonically.',    'Harmony', NULL, NULL),
('Pedal point',     'A sustained or repeated note — usually in the bass — held while the harmonies above it change.',                                            'Harmony', NULL, NULL),
('Inversion',       'When a chord is arranged so that a note other than the bottom (root) note is in the bass. First inversion has the third in the bass; second inversion has the fifth.',  'Harmony', NULL, NULL),
('Chord',           'Three or more notes sounded at the same time.',                                                                                             'Harmony', NULL, NULL),
('Dorian mode',     'A scale with a minor character but with a raised sixth degree — giving it a slightly brighter feel than a standard minor scale. Common in folk and jazz music.',  'Harmony', NULL, NULL),
('Phrygian mode',   'A scale with a minor character, distinguished by a lowered second degree — the second note of the scale is only a half-step above the first. Common in flamenco music.',  'Harmony', NULL, NULL),
('Lydian mode',     'A scale with a major character, distinguished by a raised fourth degree — the fourth note is a half-step higher than in a standard major scale. Has a bright, floating quality.',  'Harmony', NULL, NULL),
('Mixolydian mode', 'A scale with a major character but with a lowered seventh degree. Common in folk, rock and blues music.',                                   'Harmony', NULL, NULL),
('Aeolian mode',    'A natural minor scale — six notes up from the starting note of a major scale, using the same set of notes.',                                'Harmony', NULL, NULL),
('Locrian mode',    'A scale with a dark, unstable character, rarely used in practice. Its fifth note is lowered, removing the usual feeling of stability.',     'Harmony', NULL, NULL),

-- ── NOTATION ─────────────────────────────────────────────────────────────────
('Treble clef',     'The clef used for higher-pitched instruments and the right hand of keyboard music. It fixes the second line of the staff as the note G.',
 'Notation', NULL, '<span style="font-size:2em;line-height:1">𝄞</span>'),
('Bass clef',       'The clef used for lower-pitched instruments and the left hand of keyboard music. It fixes the fourth line of the staff as the note F.',
 'Notation', NULL, '<span style="font-size:1.8em;line-height:1">𝄢</span>'),
('Alto clef',       'A clef that places middle C on the middle line of the staff. Used primarily by violas.',                                                    'Notation', NULL, NULL),
('Grand staff',     'Two five-line staves joined by a brace — one for higher pitches and one for lower — used together for keyboard music.',
 'Notation', NULL,
 '<svg width="30" height="36" viewBox="0 0 30 36" style="vertical-align:middle"><line x1="6" y1="2" x2="6" y2="34" stroke="currentColor" stroke-width="1"/><line x1="8" y1="2" x2="8" y2="34" stroke="currentColor" stroke-width="2"/><line x1="8" y1="4" x2="28" y2="4" stroke="currentColor" stroke-width="1"/><line x1="8" y1="8" x2="28" y2="8" stroke="currentColor" stroke-width="1"/><line x1="8" y1="12" x2="28" y2="12" stroke="currentColor" stroke-width="1"/><line x1="8" y1="16" x2="28" y2="16" stroke="currentColor" stroke-width="1"/><line x1="8" y1="20" x2="28" y2="20" stroke="currentColor" stroke-width="1"/><line x1="8" y1="24" x2="28" y2="24" stroke="currentColor" stroke-width="1"/><line x1="8" y1="28" x2="28" y2="28" stroke="currentColor" stroke-width="1"/><line x1="8" y1="32" x2="28" y2="32" stroke="currentColor" stroke-width="1"/></svg>'),
('Key signature',   'A set of sharps or flats placed at the beginning of each line of music, indicating which notes are consistently raised or lowered throughout the piece.',
 'Notation', NULL,
 '<span style="font-size:1.2em;letter-spacing:-2px">♯♯♯</span>'),
('Bar',             'A unit of music separated by vertical lines (barlines), containing the number of beats specified at the start of the piece. Also called a measure.',
 'Notation', NULL,
 '<svg width="32" height="24" viewBox="0 0 32 24" style="vertical-align:middle"><line x1="4" y1="4" x2="28" y2="4" stroke="currentColor" stroke-width="1"/><line x1="4" y1="9" x2="28" y2="9" stroke="currentColor" stroke-width="1"/><line x1="4" y1="14" x2="28" y2="14" stroke="currentColor" stroke-width="1"/><line x1="4" y1="19" x2="28" y2="19" stroke="currentColor" stroke-width="1"/><line x1="4" y1="24" x2="28" y2="24" stroke="currentColor" stroke-width="1"/><line x1="28" y1="4" x2="28" y2="24" stroke="currentColor" stroke-width="1.5"/></svg>'),
('Double bar',      'Two barlines placed together — either marking the end of a section, or (when one line is thick) marking the end of the entire piece.',
 'Notation', NULL,
 '<svg width="16" height="20" viewBox="0 0 16 20" style="vertical-align:middle"><line x1="4" y1="2" x2="4" y2="18" stroke="currentColor" stroke-width="1.5"/><line x1="12" y1="2" x2="12" y2="18" stroke="currentColor" stroke-width="3"/></svg>'),
('Repeat sign',     'Dots placed before or after a double barline indicating that the enclosed section should be played again.',
 'Notation', NULL,
 '<svg width="24" height="20" viewBox="0 0 24 20" style="vertical-align:middle"><line x1="6" y1="2" x2="6" y2="18" stroke="currentColor" stroke-width="1.5"/><line x1="10" y1="2" x2="10" y2="18" stroke="currentColor" stroke-width="3"/><circle cx="16" cy="8" r="2.2" fill="currentColor"/><circle cx="16" cy="13" r="2.2" fill="currentColor"/></svg>'),
('First and second time bars', 'Bracketed endings for a repeated section — the first bracket is played on the first pass through; the second bracket replaces it on the repeat.',
 'Notation', NULL,
 '<svg width="44" height="20" viewBox="0 0 44 20" style="vertical-align:middle"><line x1="2" y1="14" x2="2" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="2" y1="6" x2="18" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="18" y1="6" x2="18" y2="14" stroke="currentColor" stroke-width="1.2"/><text x="6" y="13" font-size="8" fill="currentColor" font-family="serif">1.</text><line x1="24" y1="14" x2="24" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="24" y1="6" x2="42" y2="6" stroke="currentColor" stroke-width="1.2"/><text x="28" y="13" font-size="8" fill="currentColor" font-family="serif">2.</text></svg>'),
('Da capo',         'Go back to the very beginning of the piece and play again from the start. Abbreviated D.C.',                                                'Notation', 'Italian', '<em style="font-style:italic;font-size:1.0em">D.C.</em>'),
('Dal segno',       'Go back to the segno sign in the music and play again from that point. Abbreviated D.S.',                                                   'Notation', 'Italian', '<em style="font-style:italic;font-size:1.0em">D.S.</em>'),
('Fine',            'The end — marks where the piece finishes when playing a repeated section directed by a Da Capo or Dal Segno instruction.',                  'Notation', 'Italian', NULL),
('Segno',           'A sign placed in the music marking a specific point to return to when instructed.',                                                          'Notation', 'Italian', '<span style="font-size:1.5em">𝄋</span>'),
('Coda sign',       'A target-like symbol marking the beginning of a concluding section that is jumped to when instructed.',                                     'Notation', NULL, '<span style="font-size:1.5em">𝄌</span>'),
('Volta bracket',   'Numbered brackets (1., 2.) placed above the staff to show different endings for a repeated section.',
 'Notation', NULL,
 '<svg width="44" height="20" viewBox="0 0 44 20" style="vertical-align:middle"><line x1="2" y1="14" x2="2" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="2" y1="6" x2="18" y2="6" stroke="currentColor" stroke-width="1.2"/><text x="6" y="13" font-size="8" fill="currentColor" font-family="serif">1.</text><line x1="24" y1="14" x2="24" y2="6" stroke="currentColor" stroke-width="1.2"/><line x1="24" y1="6" x2="42" y2="6" stroke="currentColor" stroke-width="1.2"/><text x="28" y="13" font-size="8" fill="currentColor" font-family="serif">2.</text></svg>'),
('Ossia',           'An alternative version of a passage — typically shown on a smaller staff above or below the main staff, giving the performer a choice.',    'Notation', 'Italian', NULL),
('Semibreve',       'A note worth four beats in standard time. Also called a whole note.',
 'Notation', NULL,
 '<svg width="26" height="18" viewBox="0 0 26 18" style="vertical-align:middle"><ellipse cx="13" cy="10" rx="11" ry="6.5" stroke="currentColor" stroke-width="1.8" fill="none"/><ellipse cx="13" cy="10" rx="6" ry="3.5" fill="currentColor" transform="rotate(-20,13,10)"/></svg>'),
('Minim',           'A note worth two beats in standard time. Also called a half note.',
 'Notation', NULL,
 '<svg width="22" height="32" viewBox="0 0 22 32" style="vertical-align:middle"><ellipse cx="9" cy="24" rx="8" ry="5" stroke="currentColor" stroke-width="1.8" fill="none" transform="rotate(-15,9,24)"/><line x1="16" y1="22" x2="16" y2="3" stroke="currentColor" stroke-width="1.8"/></svg>'),
('Crotchet',        'A note worth one beat in standard time. Also called a quarter note.',
 'Notation', NULL,
 '<svg width="22" height="32" viewBox="0 0 22 32" style="vertical-align:middle"><ellipse cx="9" cy="24" rx="8" ry="5" fill="currentColor" transform="rotate(-15,9,24)"/><line x1="16" y1="22" x2="16" y2="3" stroke="currentColor" stroke-width="1.8"/></svg>'),
('Quaver',          'A note worth half a beat in standard time. Also called an eighth note.',
 'Notation', NULL,
 '<svg width="22" height="32" viewBox="0 0 22 32" style="vertical-align:middle"><ellipse cx="9" cy="24" rx="8" ry="5" fill="currentColor" transform="rotate(-15,9,24)"/><line x1="16" y1="22" x2="16" y2="3" stroke="currentColor" stroke-width="1.8"/><path d="M16,3 Q22,8 18,14" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Semiquaver',      'A note worth a quarter of a beat in standard time. Also called a sixteenth note.',
 'Notation', NULL,
 '<svg width="22" height="32" viewBox="0 0 22 32" style="vertical-align:middle"><ellipse cx="9" cy="24" rx="8" ry="5" fill="currentColor" transform="rotate(-15,9,24)"/><line x1="16" y1="22" x2="16" y2="3" stroke="currentColor" stroke-width="1.8"/><path d="M16,3 Q22,8 18,13" stroke="currentColor" stroke-width="1.5" fill="none"/><path d="M16,8 Q22,13 18,18" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>'),
('Dotted note',     'A dot placed after a note increases its value by half. A note worth two beats becomes worth three beats; a note worth one beat becomes worth one and a half beats.',
 'Notation', NULL,
 '<svg width="28" height="32" viewBox="0 0 28 32" style="vertical-align:middle"><ellipse cx="9" cy="24" rx="8" ry="5" fill="currentColor" transform="rotate(-15,9,24)"/><line x1="16" y1="22" x2="16" y2="3" stroke="currentColor" stroke-width="1.8"/><circle cx="23" cy="22" r="2.5" fill="currentColor"/></svg>'),
('Rest',            'A symbol indicating silence for a specific duration. Every note length has a matching rest symbol.',
 'Notation', NULL,
 '<svg width="52" height="20" viewBox="0 0 52 20" style="vertical-align:middle"><rect x="2" y="9" width="10" height="5" fill="currentColor"/><rect x="16" y="6" width="10" height="5" stroke="currentColor" stroke-width="1.5" fill="none"/><path d="M30,4 Q33,8 31,11 Q34,10 34,14 Q31,16 29,14 Q29,11 32,10 Q30,7 31,4 Z" fill="currentColor"/><text x="44" y="15" font-size="14" fill="currentColor" font-family="serif">𝄾</text></svg>'),
('Dynamics',        'Markings in a score that indicate how loudly or softly the music should be played.',
 'Notation', NULL,
 '<span style="font-family:serif;font-style:italic;font-weight:700;font-size:1.05em;letter-spacing:2px">pp p mf f ff</span>'),
('Tempo marking',   'A word or number placed at the start of a piece or section to indicate the speed at which it should be played.',
 'Notation', NULL,
 '<em style="font-style:italic;font-size:0.95em">Allegro ♩= 120</em>'),
('Metronome',       'A device that produces a steady, regular pulse at a chosen speed, measured in beats per minute. Used to help practise at a consistent tempo.',
 'Notation', NULL,
 '<em style="font-style:italic;font-size:0.95em">♩= 120</em>'),
('Breath mark',     'A comma-like symbol indicating where a performer should breathe or take a very brief pause.',
 'Notation', NULL,
 '<span style="font-size:1.6em;font-style:italic">''</span>'),
('8va',             'Play one octave higher than written. The marking appears above the passage with a dotted line showing where it ends.',
 'Notation', 'Italian', '<em style="font-style:italic;font-size:1.0em">8va ·····</em>'),
('Con sordino',     'With mute — play with a dampened or muted tone. On piano, this typically means to use the soft pedal.',                                     'Notation', 'Italian', NULL),
('Senza sordino',   'Without mute — remove the mute or release the soft pedal and play with a full, open tone.',                                                 'Notation', 'Italian', NULL),
('Ped.',            'Press the sustain (damper) pedal down, allowing notes to ring freely after the keys are released. The release is typically marked with an asterisk (*) or a bracket.',
 'Notation', NULL,
 '<em style="font-style:italic;font-size:1.05em">𝒫ed.</em>'),
('Divisi',          'Divide — players in a section split into two or more independent parts rather than playing the same notes.',                                  'Notation', 'Italian', NULL),
('Simile',          'Continue in the same manner as indicated in the previous bars — do not repeat the instruction each time.',                                   'Notation', 'Italian', NULL),
('Tacet',           'Be silent — do not play for an extended passage or an entire movement.',                                                                    'Notation', 'Latin', NULL)

ON CONFLICT DO NOTHING;
